const types = {
  SET_USER_INFO: 'SET_USER_INFO',
  SET_N_DATA: 'SET_N_DATA',
  TOGGLE_MSG: 'TOGGLE_MSG',
  SET_MSG: 'SET_MSG',
  SUBMISSION: {
    SET_SUBMISSION_DETAIL_QUERY_PARAM: 'SUBMISSION_SET_SUBMISSION_DETAIL_QUERY_PARAM',
  },
  PROBLEM: {
    SET_DESCRIPTION: 'PROBLEM_SET_DESCRIPTION',
    SET_CURRENT_SUBMISSION_RES_ID: 'PROBLEM_SET_CURRENT_SUBMISSION_RES_ID',
  },
}
export default types